[[GLFW]]
arch = "aarch64"
git-tree-sha1 = "13dce40e64a4b002c5fc4b6d254b7a1de42dd3ac"
os = "macos"

    [[GLFW.download]]
    sha256 = "164df61f5836759012291b3d1642493c9a30437cdad04dbdedeab19969ef4cd9"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.6+0/GLFW.v3.3.6.aarch64-apple-darwin.tar.gz"
[[GLFW]]
arch = "aarch64"
git-tree-sha1 = "e4fb48c1cda29d1e3829d78a1501b4ad21fae4f7"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "3d1eccdd76cdef9cf50938bb6833414980e6869c9ca587848268f3f84becf795"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.6+0/GLFW.v3.3.6.aarch64-linux-gnu.tar.gz"
[[GLFW]]
arch = "aarch64"
git-tree-sha1 = "d9b170242395d2c673fc8d1c0b02981e356ddab2"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "9878db163f56359029caac7a0cac70441cf4fa586e0be644c54af47af39ce262"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.6+0/GLFW.v3.3.6.aarch64-linux-musl.tar.gz"
[[GLFW]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "df04fdd078b696dceaac57f9475a40b5a36fa6ac"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "e0a139e17aefaedbf1f56d942a787fc4f02e09fd0e8b3e92f4a9a200420fef31"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.6+0/GLFW.v3.3.6.armv7l-linux-gnueabihf.tar.gz"
[[GLFW]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4afc5162731c78fe242a92c6e95d49f196b9a3ca"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "6d0dab6cd55d25a57998386be3464f9a99bc897e60ddfa5e56624c825676bd2c"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.6+0/GLFW.v3.3.6.armv7l-linux-musleabihf.tar.gz"
[[GLFW]]
arch = "i686"
git-tree-sha1 = "2c1370056cc220c0aef949590998153e9170d53a"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "88a63b7c9b944b69649a1538c74d810ff1a1a65632f0c07809b1c73d7d1ac415"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.6+0/GLFW.v3.3.6.i686-linux-gnu.tar.gz"
[[GLFW]]
arch = "i686"
git-tree-sha1 = "1475d0cc2eff4385920d12804f085a4e948dd2d7"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "f9f432c30191193c112413a17cd44d2f520fbf80bcc98ec75c13f56bdb475d3f"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.6+0/GLFW.v3.3.6.i686-linux-musl.tar.gz"
[[GLFW]]
arch = "i686"
git-tree-sha1 = "4c7e3b0c9f11b9e745a640ef98ab80f327933a2f"
os = "windows"

    [[GLFW.download]]
    sha256 = "473119b9b3f4953fd3fc87b1ce00f5c0681ef2b527b00b9d4a1ccaf929949916"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.6+0/GLFW.v3.3.6.i686-w64-mingw32.tar.gz"
[[GLFW]]
arch = "powerpc64le"
git-tree-sha1 = "a5204957df670be7b927613ea7c5a0783fd2405a"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "5043750f3ca9f42a5dd92b7288ceda0735008c2562c8e12a14b10d0bff53af85"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.6+0/GLFW.v3.3.6.powerpc64le-linux-gnu.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "3f65a58a46844070193b77b9e1e7ede47ade260d"
os = "macos"

    [[GLFW.download]]
    sha256 = "513925128f1c70d288c382e3a96529b177b50275b1421ccbae0f845b1930189a"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.6+0/GLFW.v3.3.6.x86_64-apple-darwin.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "0a865e58066f2a328a11aefbe338633a75e01423"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "403a4588ef8df28e282700f25a3bacfa69d017a4a31e4c43ca45325ba5fecabd"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.6+0/GLFW.v3.3.6.x86_64-linux-gnu.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "0e3b23e69a4c040826fd6751e7c0c30112bc69c3"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "90630bea08fbd31e6cf74fb5a9fbe85aeb6e240b737895aed123cc872fa13573"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.6+0/GLFW.v3.3.6.x86_64-linux-musl.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "6345243970276c6a108961b653edb7f6c8156f7f"
os = "freebsd"

    [[GLFW.download]]
    sha256 = "54b9fd4287a9a690ce997ba1035537e75784440d5467d2a894e50fadfd870d28"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.6+0/GLFW.v3.3.6.x86_64-unknown-freebsd.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "7cab18390919fc9354ba873996c2668e977fed42"
os = "windows"

    [[GLFW.download]]
    sha256 = "606666b78aecf2c190a7b81c983d8a7480081f4d2683d69f2dc0990d124ebff9"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.6+0/GLFW.v3.3.6.x86_64-w64-mingw32.tar.gz"
