[[GLFW]]
arch = "aarch64"
git-tree-sha1 = "fb45aec47f4839bbbefddd108977b36be80ac631"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "d335af105ac2ef22ed479a133f1d8c3f229f87ff9357e78268b4b03b826fac1d"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.2+1/GLFW.v3.3.2.aarch64-linux-gnu.tar.gz"
[[GLFW]]
arch = "aarch64"
git-tree-sha1 = "a445ed76f18d0b2bda00d0bcb41e1bdee0d7d076"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "504dbba3ecbc6191287db64dd07b73e5e7235b5f7d089cbef8ebcc43e2b936cb"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.2+1/GLFW.v3.3.2.aarch64-linux-musl.tar.gz"
[[GLFW]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a4a549eed6e60b17b574ce8e87d0572d57f93756"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "843d225146d176ba7fdfdae7648b2623d1fbd05ae696ad69745c926030a06cac"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.2+1/GLFW.v3.3.2.armv7l-linux-gnueabihf.tar.gz"
[[GLFW]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e3631bcd2a9192402eb10bca2949e4234bc1376f"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "544d4c70d242be980e2e9b3245b948e8fdbb15cdd93a5286b5d4338c8110bce8"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.2+1/GLFW.v3.3.2.armv7l-linux-musleabihf.tar.gz"
[[GLFW]]
arch = "i686"
git-tree-sha1 = "6bf0c34326366971aeaafd2b3bc95ced31f8471a"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "d928618bbc5960869a5d0063accf18f5ac8637f6d0f6aa31b007fe3ab7fb6d01"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.2+1/GLFW.v3.3.2.i686-linux-gnu.tar.gz"
[[GLFW]]
arch = "i686"
git-tree-sha1 = "4526761b4683af1ffbca1008f3c257f3c8d16c58"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "29e58623c50bfed0b97dabf1b3a5ed0a74145600520b5e07eb77f768febcb253"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.2+1/GLFW.v3.3.2.i686-linux-musl.tar.gz"
[[GLFW]]
arch = "i686"
git-tree-sha1 = "b3bb1073a4465c928964314ad63e84837f768a05"
os = "windows"

    [[GLFW.download]]
    sha256 = "9e2ef178df69b9b32bc27e92ee48444ebd601f2d4dda26fee550d56df75aec34"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.2+1/GLFW.v3.3.2.i686-w64-mingw32.tar.gz"
[[GLFW]]
arch = "powerpc64le"
git-tree-sha1 = "1f810f55fedd6be841c33e90403069e42aa93038"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "12561c8a451e393ab7264194d5bcafea442416e0a4e02b222faf4ad0fd7eab04"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.2+1/GLFW.v3.3.2.powerpc64le-linux-gnu.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "81dbbcaad7406eabd969e7044076c56d9b2174ed"
os = "macos"

    [[GLFW.download]]
    sha256 = "4665971011fc0d2fd5fc904026b480b40a9b8ff8d53b9324e09ab12b89121b69"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.2+1/GLFW.v3.3.2.x86_64-apple-darwin.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "48ea4f1374cd7ef7e81e416d5f3e981d444883a6"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "f7be9fd45d04d739dafea63549dfff7cd6eeace5c8322a0e109b20e98fc330a8"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.2+1/GLFW.v3.3.2.x86_64-linux-gnu.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "ab840c87d03f48dd84d1d31f4053f3cb99f8b803"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "2a12a3ff6033ce57216eb2c4588b0dd6cf5c316121af1d1c5856c7dd6b777226"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.2+1/GLFW.v3.3.2.x86_64-linux-musl.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "1dc16c3734a20bc97fe20bebea416fb96a19b447"
os = "freebsd"

    [[GLFW.download]]
    sha256 = "5034b8f0be4061bf1f024fd1084818005bd5f6fb7309e935cd59f578e031a85d"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.2+1/GLFW.v3.3.2.x86_64-unknown-freebsd.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "c33d43da605a932606adb324efb2a13f272dbaac"
os = "windows"

    [[GLFW.download]]
    sha256 = "500576ac8c3812f10b6ed70d6defe1c47f6dc8578b1bf7867a92a3df6618b2ad"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.2+1/GLFW.v3.3.2.x86_64-w64-mingw32.tar.gz"
