[[GLFW]]
arch = "aarch64"
git-tree-sha1 = "7f4d1479db8bfb628aff3806c483e5fec617271a"
os = "macos"

    [[GLFW.download]]
    sha256 = "47df3bbae2f5cc3b6b07d7ff69ac2106c6a2f337fba4bbf2ce65c71cf64b6be8"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.8+0/GLFW.v3.3.8.aarch64-apple-darwin.tar.gz"
[[GLFW]]
arch = "aarch64"
git-tree-sha1 = "c3d42a238e767ebc822120f05deac5c1a0fea9b2"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "790662181e8f07dc9e62072d011d34e4f3d9086acd01d899801bee293a1410a5"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.8+0/GLFW.v3.3.8.aarch64-linux-gnu.tar.gz"
[[GLFW]]
arch = "aarch64"
git-tree-sha1 = "9dcea7d4f4b2003e6213ac67375e6fb73e4dc8cf"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "caa342b2e73cefe9f529390d5450c39a136cf6bc1e7d31f16fab197fcba76d53"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.8+0/GLFW.v3.3.8.aarch64-linux-musl.tar.gz"
[[GLFW]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ea1148952796139c7f90d74ddd1f862978c7a20c"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "d6681d6486bbf9f35b612d7c87d4324bf3391f6a7836404dd3bda95a078340a9"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.8+0/GLFW.v3.3.8.armv7l-linux-gnueabihf.tar.gz"
[[GLFW]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "291f833c75b6baec285bf927414f4629916ff4db"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "987eb7e12501aebe3a73145763cfa65bc90867e3f786a21675e4db6bb27cd4d0"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.8+0/GLFW.v3.3.8.armv7l-linux-musleabihf.tar.gz"
[[GLFW]]
arch = "i686"
git-tree-sha1 = "db10302f4f3e502f9bac7aa4f7aab5ac4f472ff4"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "8411a8fb8672a9ad7d5678cfb9d5ab5da29f238f81f10a76ecdc4a08f87b9200"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.8+0/GLFW.v3.3.8.i686-linux-gnu.tar.gz"
[[GLFW]]
arch = "i686"
git-tree-sha1 = "c3add6b4b49b0712fd800e2050ba1dfb33bbe692"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "195f5bfcdeb9deb2c9c5e61a5410f93c56be6515cb32b1b93c585ac2a230202e"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.8+0/GLFW.v3.3.8.i686-linux-musl.tar.gz"
[[GLFW]]
arch = "i686"
git-tree-sha1 = "229fcb3c011e2e825afc3f7ab4ef95e63807d744"
os = "windows"

    [[GLFW.download]]
    sha256 = "85b2f85676542c972590fe97cdd39e0e868dfb4f755f8aff673f1f46c9d1dff7"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.8+0/GLFW.v3.3.8.i686-w64-mingw32.tar.gz"
[[GLFW]]
arch = "powerpc64le"
git-tree-sha1 = "d08e2a17eb1a7b91b98f807108f9f86b3651f842"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "56b852aa878869558c49c9bf5cf2266c8114c9dc0c56aa05583bd10a489e6f84"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.8+0/GLFW.v3.3.8.powerpc64le-linux-gnu.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "54253779fac0a65601dab59d1e7249b501ff9f71"
os = "macos"

    [[GLFW.download]]
    sha256 = "13c3405792064f4e5a73530abecf5b4e55b7652cd60c3912a9979c9fc62f4c75"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.8+0/GLFW.v3.3.8.x86_64-apple-darwin.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "5aa80c7b8e919cbfee41019069d9b25269befe10"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "77914b7ba66ccb288a018f1fba65ec8c383e17519732c23ef36fcc2adfb179eb"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.8+0/GLFW.v3.3.8.x86_64-linux-gnu.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "853ab93a2382e51ea81f4e13d943446759cd550d"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "c92fd566951e9191ec359f311e3093f1976c013cb326895d1e0aff32f94ffb00"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.8+0/GLFW.v3.3.8.x86_64-linux-musl.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "cbb9f92bc2da5ced18094b02b37161dd900fd66e"
os = "freebsd"

    [[GLFW.download]]
    sha256 = "2ec9b98c9b209ecfaba87306958c56e178e032b7abbe00468a2cacf540a1f3e0"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.8+0/GLFW.v3.3.8.x86_64-unknown-freebsd.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "09afce8db647ca1b603103c82397809ce7189340"
os = "windows"

    [[GLFW.download]]
    sha256 = "8b7fd08241372578af284204308895358300c7877668f08e5e7a17fc4e4a96b0"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.8+0/GLFW.v3.3.8.x86_64-w64-mingw32.tar.gz"
