[[GLFW]]
arch = "aarch64"
git-tree-sha1 = "8dfccc7f1aa9d156f12a6e7db599014b805b11f2"
os = "macos"

    [[GLFW.download]]
    sha256 = "029dd0f914d55bf707958ea086fb15719c8cea69a9e00834d3aedaef35477ecf"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.9+0/GLFW.v3.3.9.aarch64-apple-darwin.tar.gz"
[[GLFW]]
arch = "aarch64"
git-tree-sha1 = "d6fdd37949f01a2f518a508d01c05042613fa392"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "83643310d84596f27cd11d0e7403bdf121b6ea4222bd0d5e0cc7fecaa84e6552"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.9+0/GLFW.v3.3.9.aarch64-linux-gnu.tar.gz"
[[GLFW]]
arch = "aarch64"
git-tree-sha1 = "d0e927115713c369f43d72af9fe78c0c27939c0c"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "6b7e49d44f486ce95ab906f3b6ed18e7da39da67df47d3d9804850d6c334efdd"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.9+0/GLFW.v3.3.9.aarch64-linux-musl.tar.gz"
[[GLFW]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1fb110b5916b948d0c56cd72fed94cab8b574d85"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "9512509c183ce3fe3db789c3e2cd3398fa6a37cb72a51999b00f015011d0cc5a"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.9+0/GLFW.v3.3.9.armv7l-linux-gnueabihf.tar.gz"
[[GLFW]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6c40fe6ce9e59823ec81b66df4c77d6278ffa1a6"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "70f7be11eeb8557359003e88a6e6174b570f941954aacd62209ee20c90d12e7e"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.9+0/GLFW.v3.3.9.armv7l-linux-musleabihf.tar.gz"
[[GLFW]]
arch = "i686"
git-tree-sha1 = "0e4e1c9e1c10d6f8c5984483860d1de17bea584f"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "b04235af0778cbb8e3e10cb646a02bbe2c1298165a61a207e8de822de9154e5c"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.9+0/GLFW.v3.3.9.i686-linux-gnu.tar.gz"
[[GLFW]]
arch = "i686"
git-tree-sha1 = "edbf41a9da2a9c8c109c21974e3943a752e13aac"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "dced9454be8496bb1d6e6b0c9a811724a098e32667e19b711e66d85623359f45"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.9+0/GLFW.v3.3.9.i686-linux-musl.tar.gz"
[[GLFW]]
arch = "i686"
git-tree-sha1 = "85dd091194f0c3542b42eb6dde96742ccb465c31"
os = "windows"

    [[GLFW.download]]
    sha256 = "42e8cfde99e711a918729c3e9c52fce0927ef778e78a45c46c61b6ba8e5ae321"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.9+0/GLFW.v3.3.9.i686-w64-mingw32.tar.gz"
[[GLFW]]
arch = "powerpc64le"
git-tree-sha1 = "6ad0e0b6ad40520d6b256637f1335f57bad1f973"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "1f5810a1252aac0e374232a3f002b270338e316448df076c67bdbaa2f8878f25"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.9+0/GLFW.v3.3.9.powerpc64le-linux-gnu.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "9fc071d4d02693a94bf56670806ecdb81b3a2d5d"
os = "macos"

    [[GLFW.download]]
    sha256 = "b672139ab7ba5e515fc5b663aa5d84df7eacc46a862f405a45ce6ae1874e2a2d"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.9+0/GLFW.v3.3.9.x86_64-apple-darwin.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "1669295ef2dc7a3244d961c3d1a619bfdc9465dc"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "de7292dd9242614cb9eab1ac12c2bc9e038372c2233c20c161366855125ce777"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.9+0/GLFW.v3.3.9.x86_64-linux-gnu.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "25cabeb27e2983dfdf43e564c82ed7fcc6f5be7f"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "275abd115940fcc29c7ce46f64e10939bcebf19631aaa9b83edcd9eb2f7e85eb"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.9+0/GLFW.v3.3.9.x86_64-linux-musl.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "21f8607cfd4ff3251f5a8ac1569a149a0d8f96a8"
os = "freebsd"

    [[GLFW.download]]
    sha256 = "aa1758d4558d195846e28719ffad28945c9e52629dba02708aabf6e2e43c709d"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.9+0/GLFW.v3.3.9.x86_64-unknown-freebsd.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "6d3ef37931c0b327b1dff2a9e0d1e2d0a835082c"
os = "windows"

    [[GLFW.download]]
    sha256 = "e1b73c64544d5a46646f6c1954612c94495a620a66b6299971f3b656cd8f70e9"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.9+0/GLFW.v3.3.9.x86_64-w64-mingw32.tar.gz"
