[[GLFW]]
arch = "aarch64"
git-tree-sha1 = "54c650f7b5f1371d0a372cd7daaf318153a9a77f"
os = "macos"

    [[GLFW.download]]
    sha256 = "85287f1f4e4b710e586d557baf0c3c454318af061c8f3019038bfbc37c345af4"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.5.1+0/GLFW.v3.5.1.aarch64-apple-darwin.tar.gz"
[[GLFW]]
arch = "aarch64"
git-tree-sha1 = "e010732b5e39e89b3b88f5b8e273a0c7fa525f93"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "8a938766277ed5d9269b1349dc3af5563ae18c8ea9320c61df32ee8bf47af6af"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.5.1+0/GLFW.v3.5.1.aarch64-linux-gnu.tar.gz"
[[GLFW]]
arch = "aarch64"
git-tree-sha1 = "bdc81c470fe5c485aced8a8b6491d8bd214be4fc"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "696c455a9244bb9648503541c9cb857be186a7dd832fce11b51658e5fc2071e9"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.5.1+0/GLFW.v3.5.1.aarch64-linux-musl.tar.gz"
[[GLFW]]
arch = "aarch64"
git-tree-sha1 = "cd3848571428310351af204e4043efb02607aafb"
os = "freebsd"

    [[GLFW.download]]
    sha256 = "a84b646a3bf189d7852278dd7a1f06e015df2043526b5726b3a26c9cb6f0fad3"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.5.1+0/GLFW.v3.5.1.aarch64-unknown-freebsd.tar.gz"
[[GLFW]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9e902fef2f8e8a532c8ff2ca80a32fe79f2d7363"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "c7847de3b67a1f768adcd5e7f3c91426f2b5d753cdb7eb319f2d8d52d64cf183"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.5.1+0/GLFW.v3.5.1.armv7l-linux-gnueabihf.tar.gz"
[[GLFW]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f1db84a4eebdb1ba043d01450d96b394e3a26988"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "4a8bde4cff0c21bfb97afc9c21f7180fa472686166f6940dcca748cf153a7cda"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.5.1+0/GLFW.v3.5.1.armv7l-linux-musleabihf.tar.gz"
[[GLFW]]
arch = "i686"
git-tree-sha1 = "4966db6a2ba2ce98f7f98b65c70b9490d095fc65"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "9ca9eac302193d64ea75677dcdcab778042541bc292063e1e5f24f065fdacff9"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.5.1+0/GLFW.v3.5.1.i686-linux-gnu.tar.gz"
[[GLFW]]
arch = "i686"
git-tree-sha1 = "1516641a9c722553f7cdfcd6bfd20c3ba365823e"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "7aed8d08ece59ddc9190a0bbd09911173ee64d236bbe235cf8819d9c88ccdde6"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.5.1+0/GLFW.v3.5.1.i686-linux-musl.tar.gz"
[[GLFW]]
arch = "i686"
git-tree-sha1 = "b616a466396543e326fb077ad463c963f7cd5955"
os = "windows"

    [[GLFW.download]]
    sha256 = "0cb5330c6ef9262623e64e1f531530620fc4ac83774425365a38c81dfc23c584"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.5.1+0/GLFW.v3.5.1.i686-w64-mingw32.tar.gz"
[[GLFW]]
arch = "powerpc64le"
git-tree-sha1 = "c5176b63b26533d62792515ce9b6d62f68de5d88"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "b8fd7729d48cadf5c91b93ee80eb0bb365092a70f7453fc76537772dd6982afc"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.5.1+0/GLFW.v3.5.1.powerpc64le-linux-gnu.tar.gz"
[[GLFW]]
arch = "riscv64"
git-tree-sha1 = "5de69e8771df182fa60f2066ad14f146a6fc898b"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "ed6b97ed53d7e633866c1ee36c0162d9e967db1070eff7b45f879ffa0c75d989"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.5.1+0/GLFW.v3.5.1.riscv64-linux-gnu.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "a2c3b2bdf7007f155ac2f2178510d8021e0e48d1"
os = "macos"

    [[GLFW.download]]
    sha256 = "c04e9a8cbe08f3b5f78168eba3dc47344656bd208244b0183dc54b5af2f5e21d"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.5.1+0/GLFW.v3.5.1.x86_64-apple-darwin.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "0157b24bcebb034bdcfc98afd4869f05275d2c11"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "4ef712df8e0e221db1d19f77dd7f023ac4758a9c9def84ecdd382af0616b900a"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.5.1+0/GLFW.v3.5.1.x86_64-linux-gnu.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "a72d406123b23632a411cc1fa778b7401f44abe8"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "40afec7711f0829cbe431e28234e2272725dfc726e02dc71d8678aab71c72299"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.5.1+0/GLFW.v3.5.1.x86_64-linux-musl.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "5ea8a932ebe21041630076e23183f287bc78edbd"
os = "freebsd"

    [[GLFW.download]]
    sha256 = "a06a9e6c89ede3f87ab81d8d4e082b5afa4b4dd219243c3b02507df712cca5d0"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.5.1+0/GLFW.v3.5.1.x86_64-unknown-freebsd.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "52a9366bacf21a0ab8d184f00c3098bea354d625"
os = "windows"

    [[GLFW.download]]
    sha256 = "196e10143f19d8144aad9faa7d9c362b965a7035f551b9d4de5a665945155bd0"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.5.1+0/GLFW.v3.5.1.x86_64-w64-mingw32.tar.gz"
