[[GLFW]]
arch = "aarch64"
git-tree-sha1 = "37a656227e9765432a39c88cf2ba7d1ddfee4d61"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "ddb69257160185916bc6e75f81d2c4bc4b824ac717b7ed0dec069640abb16e9a"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.3+0/GLFW.v3.3.3.aarch64-linux-gnu.tar.gz"
[[GLFW]]
arch = "aarch64"
git-tree-sha1 = "2d07d58a25163179470e33d4677db956991cfe93"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "4f68efbbde0c05328c3cbe36e662fd283859ec86b395c46192b4e9cf4cfc539b"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.3+0/GLFW.v3.3.3.aarch64-linux-musl.tar.gz"
[[GLFW]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ba26ffcf011bedf022c049a6434299b43e4747f9"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "4275db283e4b1ee6175e633645a13d169dc91b38a6782bf2df42f522d4090339"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.3+0/GLFW.v3.3.3.armv7l-linux-gnueabihf.tar.gz"
[[GLFW]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a05570bc36bbba084140c7158899259d4dec9de0"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "4f25e5e42aa3fca80cdef27fbc1b80fc9a837790bc7702a40281162615de0d91"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.3+0/GLFW.v3.3.3.armv7l-linux-musleabihf.tar.gz"
[[GLFW]]
arch = "i686"
git-tree-sha1 = "a8309f5970076c6769f9c902c37dd74ccc85752c"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "1fd7919b56ea3769d1c1477d7e8b1f59151402d36335e19472f2b067ece890c9"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.3+0/GLFW.v3.3.3.i686-linux-gnu.tar.gz"
[[GLFW]]
arch = "i686"
git-tree-sha1 = "2ca81ca2133819dc43d9248e42b0ef34bd179dfe"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "af6ef713935f6927cdfb809a97f0fd95aa12d55d59049d77edd0b6ff2c000588"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.3+0/GLFW.v3.3.3.i686-linux-musl.tar.gz"
[[GLFW]]
arch = "i686"
git-tree-sha1 = "5c69d5466ea3997918574cb1c32c5af769855574"
os = "windows"

    [[GLFW.download]]
    sha256 = "74bae5332e3961f50c092590517bc7023dda46203cf54cacfebc160111102ee0"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.3+0/GLFW.v3.3.3.i686-w64-mingw32.tar.gz"
[[GLFW]]
arch = "powerpc64le"
git-tree-sha1 = "339338ca59a775c39c8a8cc63a5406b131686f27"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "faa1e01f2d5dcb892a119f8d3369cad54c8c9f78a813ee97c350ff6f82064660"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.3+0/GLFW.v3.3.3.powerpc64le-linux-gnu.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "fcc175955379346afe4623b38d8ece066368e338"
os = "macos"

    [[GLFW.download]]
    sha256 = "23423fda9d4473b95abfa8b345852eb2db9cbe646a5807b34ea0ce29d922e817"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.3+0/GLFW.v3.3.3.x86_64-apple-darwin.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "ded9d2caacc9a40cabeae1e02a77a310247f81b8"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "54507c3f4fde4031684b9259398d8d9754958aefb0db02aa23157e0723e0ed59"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.3+0/GLFW.v3.3.3.x86_64-linux-gnu.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "13394fd01d8b40e13fc66bdc2ec2485bc7307aea"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "29f3b8a4c5fd68b2ca22375e51d9524fe20acb424d065e01dc5f27e2af073e81"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.3+0/GLFW.v3.3.3.x86_64-linux-musl.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "40c30793c9f47711bb2a65b9786386e9d5de12c2"
os = "freebsd"

    [[GLFW.download]]
    sha256 = "776048c344025d472ccc4bd2741a9d30388fde171828e2683111fd16f6874619"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.3+0/GLFW.v3.3.3.x86_64-unknown-freebsd.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "9e93cd93728be579c37bc830c8d9707ad60d4525"
os = "windows"

    [[GLFW.download]]
    sha256 = "d683493cf53b365b13c6b8e550c2cbfddf8785b920f76a87800606521cc53c24"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.3.3+0/GLFW.v3.3.3.x86_64-w64-mingw32.tar.gz"
