[[GLFW]]
arch = "aarch64"
git-tree-sha1 = "80bb151e4d99a3b40bf88216dc326e34c0a62c30"
os = "macos"

    [[GLFW.download]]
    sha256 = "09f6e4a7ba8e33da63f55660e0d5715605f131c0f9ddc94f1c0515909eab1e59"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+1/GLFW.v3.4.1.aarch64-apple-darwin.tar.gz"
[[GLFW]]
arch = "aarch64"
git-tree-sha1 = "6331382f6da4ed384128b87ca7506b9f673c8677"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "85b2b70f3d6e235c1e06954846a471a3be6a7383541ad202542e5530d5efa24e"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+1/GLFW.v3.4.1.aarch64-linux-gnu.tar.gz"
[[GLFW]]
arch = "aarch64"
git-tree-sha1 = "524a147ea32d348dad3fde37f3da8f1367d9068d"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "119ba911de3af3e03937b8678b4363ea7b3a07b08dbf3a91bb9d8fc22ef3bd2d"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+1/GLFW.v3.4.1.aarch64-linux-musl.tar.gz"
[[GLFW]]
arch = "aarch64"
git-tree-sha1 = "d81b1ef19323cab3ad9e365f155efc90275a6a48"
os = "freebsd"

    [[GLFW.download]]
    sha256 = "c5b78a7e7d5a5b3a2f93829e7968f64d4e9de528122efd8d77ff75927d595f82"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+1/GLFW.v3.4.1.aarch64-unknown-freebsd.tar.gz"
[[GLFW]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d51d315b86a4e8a29c47446003247f48c58d195e"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "4d7e643659aa0435883215e83e61bf844338ac367a227e4da710e09ee2b02837"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+1/GLFW.v3.4.1.armv7l-linux-gnueabihf.tar.gz"
[[GLFW]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7e6dbd755d97598ff649c7e26d209d5e94f5a0cc"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "0474e33192a2efd1e73a0ab7136e2cf7dff0ad9d2c869bd934adcfffc8976d22"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+1/GLFW.v3.4.1.armv7l-linux-musleabihf.tar.gz"
[[GLFW]]
arch = "i686"
git-tree-sha1 = "d9170250753612a80b94924f8a46781be9b9b537"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "a46130b19e98bff47f69b22e4e2da0ad1bc7690c9af8ae29663b9e625898301a"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+1/GLFW.v3.4.1.i686-linux-gnu.tar.gz"
[[GLFW]]
arch = "i686"
git-tree-sha1 = "a664dbf80a712b71b922167262ac52690a47bff0"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "cd5ebbd93a9625a2fbdf7dfc7770b4a9de1df154ffc5a2636403cdf97c4d53c3"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+1/GLFW.v3.4.1.i686-linux-musl.tar.gz"
[[GLFW]]
arch = "i686"
git-tree-sha1 = "05daa9a68a1db6e3c898053943f032782384e71a"
os = "windows"

    [[GLFW.download]]
    sha256 = "a44e807b649c62c46fc08fa9b89c4a977fc2e2eb8ac134a21deb0b7d07b4bbe7"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+1/GLFW.v3.4.1.i686-w64-mingw32.tar.gz"
[[GLFW]]
arch = "powerpc64le"
git-tree-sha1 = "f77b4c1293e5b61a4719becc6b7ab491417230f4"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "397f1f980c5d3292478c2a74877950e14aef8571b0bed49604cb7034f48de27d"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+1/GLFW.v3.4.1.powerpc64le-linux-gnu.tar.gz"
[[GLFW]]
arch = "riscv64"
git-tree-sha1 = "ac3f7d849ea11c98471e5b704896ab5a2d552791"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "9f09a8135c5a6cd6aa237866384b0ad34530c811c180d54f8762de2b98bbe11c"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+1/GLFW.v3.4.1.riscv64-linux-gnu.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "7fc996538bb280af3b482680df0d8f5c05e9c39a"
os = "macos"

    [[GLFW.download]]
    sha256 = "a989bf57501cb44b82e557e99e8492dacd1fc4c90960c81177102adacccc9e49"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+1/GLFW.v3.4.1.x86_64-apple-darwin.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "8f3b1d9a0b13295e614fda5876b2352781c0fd90"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "5be3a86158e1fc8d39ac06e2549f0707560f21b85db7bb702fc0de8ed2e51c8f"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+1/GLFW.v3.4.1.x86_64-linux-gnu.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "1d7f037bfa675a5341d4cb399466fd0550f61264"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "1430790f257483831c39a8c993942308613bf4696f9991ea08ad08f2b9bf511d"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+1/GLFW.v3.4.1.x86_64-linux-musl.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "9959f33498c83ddc10d25f38b60ffb29cd1a630f"
os = "freebsd"

    [[GLFW.download]]
    sha256 = "b462ef3cdaacc7723e2011ee5e3798153a2637ae8c5b15b1c82fc0245d62ff9d"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+1/GLFW.v3.4.1.x86_64-unknown-freebsd.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "31c6e32b51ce59ee34d3a80cb82ff162501e374a"
os = "windows"

    [[GLFW.download]]
    sha256 = "41312be975c72dfa330795dd9784523b767ecf76c6f9fab2682a126b35c7281a"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+1/GLFW.v3.4.1.x86_64-w64-mingw32.tar.gz"
